"use client";

import { useMemo, useState } from "react";
import { ArrowDownRight, ArrowUpRight, BarChart3, CalendarDays, Check, Download, FileText, Filter, Layers3, RefreshCw, Sparkles, TrendingUp, Users } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Modal } from "@/components/ui/modal";
import { formatCurrency, reportChannels, reportSegments } from "@/lib/crm-data";

const periods = ["Últimos 30 dias", "Últimos 90 dias", "Este ano"];
const trendValues = [32, 38, 35, 48, 55, 63, 68, 76, 83, 89, 96, 108];

function RevenueTrend() {
  const points = trendValues.map((value, index) => `${index * 8.6 + 2},${122 - value}`).join(" ");
  const area = `2,122 ${points} 98.6,122`;
  return <div className="relative mt-5 h-56 overflow-hidden rounded-xl border border-border-subtle bg-background/60 p-3"><div className="pointer-events-none absolute inset-0 bg-[linear-gradient(to_bottom,transparent_24%,rgba(20,22,25,0.06)_25%,transparent_26%,transparent_49%,rgba(20,22,25,0.06)_50%,transparent_51%,transparent_74%,rgba(20,22,25,0.06)_75%,transparent_76%)]" /><svg viewBox="0 0 100 130" preserveAspectRatio="none" className="relative h-full w-full" aria-label="Tendência de receita"><defs><linearGradient id="report-area" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#C09B32" stopOpacity="0.28" /><stop offset="100%" stopColor="#C09B32" stopOpacity="0.02" /></linearGradient></defs><polygon points={area} fill="url(#report-area)" /><polyline points={points} fill="none" stroke="#C09B32" strokeWidth="1.2" vectorEffect="non-scaling-stroke" strokeLinecap="round" strokeLinejoin="round" />{trendValues.map((value, index) => <circle key={index} cx={index * 8.6 + 2} cy={122 - value} r="1.15" fill="#FFFFFF" stroke="#C09B32" strokeWidth="0.8" vectorEffect="non-scaling-stroke" />)}</svg><div className="absolute bottom-2 left-3 right-3 flex justify-between text-[10px] font-medium text-muted-foreground"><span>01 Ago</span><span>08 Ago</span><span>15 Ago</span><span>22 Ago</span><span>Hoje</span></div></div>;
}

export function ReportsContent() {
  const [period, setPeriod] = useState(periods[0]);
  const [reportType, setReportType] = useState("Visão executiva");
  const [exportOpen, setExportOpen] = useState(false);
  const [exportMessage, setExportMessage] = useState<string | null>(null);
  const topChannel = useMemo(() => [...reportChannels].sort((a, b) => b.revenue - a.revenue)[0], []);

  return (
    <div className="space-y-7 pb-12">
      <div className="flex flex-col gap-5 border-b border-border-subtle pb-6 lg:flex-row lg:items-end lg:justify-between"><div><div className="mb-3 inline-flex items-center gap-2 text-[11px] font-semibold text-muted-foreground"><BarChart3 className="h-3.5 w-3.5 text-accent" /> Leitura de negócio</div><h2 className="text-[1.85rem] font-extrabold tracking-[-0.04em] text-foreground sm:text-3xl">Relatórios</h2><p className="mt-2 max-w-2xl text-xs leading-relaxed text-muted-foreground sm:text-sm">Transforme o histórico de clientes, pedidos e canais em decisões para a próxima jornada.</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" size="sm" onClick={() => setExportOpen(true)} className="h-9 text-xs font-semibold"><Download className="h-3.5 w-3.5" /> Exportar</Button><Button variant="accent" size="sm" onClick={() => setExportMessage("Dados actualizados agora.")} className="h-9 text-xs font-semibold"><RefreshCw className="h-3.5 w-3.5" /> Actualizar</Button></div></div>

      <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div className="flex flex-wrap gap-1 rounded-xl border border-border bg-card p-1 shadow-sm">{["Visão executiva", "Clientes", "Canais"].map((type) => <button key={type} type="button" onClick={() => setReportType(type)} className={`rounded-lg px-3 py-2 text-[11px] font-bold transition-colors ${reportType === type ? "bg-foreground text-primary-foreground" : "text-muted-foreground hover:bg-muted hover:text-foreground"}`}>{type}</button>)}</div><div className="flex flex-wrap items-center gap-2"><Filter className="h-3.5 w-3.5 text-muted-foreground" />{periods.map((item) => <button key={item} type="button" onClick={() => setPeriod(item)} className={`rounded-lg border px-3 py-2 text-[11px] font-semibold transition-colors ${period === item ? "border-accent bg-accent/10 text-accent" : "border-border bg-card text-muted-foreground hover:bg-muted"}`}>{item}</button>)}</div></div>

      <section aria-label="Indicadores principais" className="grid grid-cols-1 gap-3 sm:grid-cols-2 xl:grid-cols-4"><article className="card-surface border-l-2 border-l-accent p-4 sm:p-5"><div className="flex items-center justify-between"><p className="page-kicker">Receita atribuída</p><TrendingUp className="h-4 w-4 text-accent" /></div><p className="mt-4 text-2xl font-extrabold tracking-[-0.04em]">R$ 128.560,00</p><p className="mt-2 text-[11px] font-bold text-success"><ArrowUpRight className="mr-0.5 inline h-3 w-3" />12,5% <span className="font-medium text-muted-foreground">vs período anterior</span></p></article><article className="card-surface p-4 sm:p-5"><div className="flex items-center justify-between"><p className="page-kicker">Pedidos atribuídos</p><Layers3 className="h-4 w-4 text-muted-foreground" /></div><p className="mt-4 text-2xl font-extrabold tracking-[-0.04em]">3.440</p><p className="mt-2 text-[11px] font-bold text-success"><ArrowUpRight className="mr-0.5 inline h-3 w-3" />9,8% <span className="font-medium text-muted-foreground">no período</span></p></article><article className="card-surface p-4 sm:p-5"><div className="flex items-center justify-between"><p className="page-kicker">Clientes activos</p><Users className="h-4 w-4 text-muted-foreground" /></div><p className="mt-4 text-2xl font-extrabold tracking-[-0.04em]">2.847</p><p className="mt-2 text-[11px] font-bold text-success"><ArrowUpRight className="mr-0.5 inline h-3 w-3" />12,4% <span className="font-medium text-muted-foreground">na base</span></p></article><article className="card-surface border-l-2 border-l-rose-400 p-4 sm:p-5"><div className="flex items-center justify-between"><p className="page-kicker">Clientes em risco</p><ArrowDownRight className="h-4 w-4 text-rose-500" /></div><p className="mt-4 text-2xl font-extrabold tracking-[-0.04em]">72</p><p className="mt-2 text-[11px] font-bold text-success"><ArrowDownRight className="mr-0.5 inline h-3 w-3" />4,1% <span className="font-medium text-muted-foreground">vs período anterior</span></p></article></section>

      <section className="grid gap-4 xl:grid-cols-[minmax(0,1.45fr)_minmax(320px,0.75fr)]"><article className="data-surface p-4 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="page-kicker">{reportType}</p><h3 className="mt-1 text-base font-bold tracking-tight text-foreground">Evolução da receita</h3><p className="mt-1 text-[11px] text-muted-foreground">{period} · vendas atribuídas a clientes identificados</p></div><div className="text-right"><p className="text-2xl font-extrabold tracking-[-0.04em] text-foreground">R$ 128.560,00</p><p className="mt-1 text-[11px] font-bold text-success">+12,5% no período</p></div></div><RevenueTrend /></article><aside className="data-surface flex flex-col p-4 sm:p-6"><div className="flex items-start justify-between gap-3"><div><p className="page-kicker">Sinal do período</p><h3 className="mt-1 text-base font-bold tracking-tight text-foreground">O que merece atenção</h3></div><Sparkles className="h-4 w-4 text-accent" /></div><div className="mt-5 rounded-xl border border-accent/20 bg-accent/5 p-4"><p className="text-sm font-bold leading-relaxed text-foreground">{topChannel.label} concentra {topChannel.share} da receita identificada.</p><p className="mt-2 text-[11px] leading-relaxed text-muted-foreground">A origem responde por {topChannel.orders.toLocaleString("pt-BR")} pedidos. A próxima oportunidade está nos clientes prontos para recompra.</p></div><div className="mt-4 space-y-3"><div className="flex items-center justify-between border-b border-border-subtle pb-3 text-xs"><span className="text-muted-foreground">Segmento prioritário</span><strong className="text-foreground">386 prontos</strong></div><div className="flex items-center justify-between border-b border-border-subtle pb-3 text-xs"><span className="text-muted-foreground">Conversão do segmento</span><strong className="text-foreground">34,6%</strong></div><div className="flex items-center justify-between text-xs"><span className="text-muted-foreground">Receita potencial</span><strong className="text-accent">R$ 36.480,00</strong></div></div></aside></section>

      <section className="grid gap-4 xl:grid-cols-2"><article className="data-surface overflow-hidden"><div className="flex items-center justify-between border-b border-border-subtle px-4 py-4 sm:px-5"><div><p className="page-kicker">Canais de venda</p><h3 className="mt-1 text-base font-bold tracking-tight">Receita por origem</h3></div><FileText className="h-4 w-4 text-muted-foreground" /></div><div className="divide-y divide-border-subtle">{reportChannels.map((channel) => <div key={channel.label} className="flex items-center gap-3 px-4 py-3.5 sm:px-5"><div className={`flex h-9 w-9 shrink-0 items-center justify-center rounded-lg text-[10px] font-extrabold text-white ${channel.color}`}>{channel.short}</div><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-3"><p className="truncate text-xs font-bold text-foreground">{channel.label}</p><p className="shrink-0 text-xs font-bold text-foreground">{formatCurrency(channel.revenue)}</p></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-muted"><div className={`h-full rounded-full ${channel.color}`} style={{ width: channel.share }} /></div><div className="mt-1 flex justify-between text-[10px] text-muted-foreground"><span>{channel.orders.toLocaleString("pt-BR")} pedidos</span><span>{channel.share} do total</span></div></div></div>)}</div></article><article className="data-surface overflow-hidden"><div className="flex items-center justify-between border-b border-border-subtle px-4 py-4 sm:px-5"><div><p className="page-kicker">Segmentos</p><h3 className="mt-1 text-base font-bold tracking-tight">Valor e conversão por grupo</h3></div><Users className="h-4 w-4 text-muted-foreground" /></div><div className="divide-y divide-border-subtle">{reportSegments.map((segment) => <div key={segment.label} className="grid grid-cols-[minmax(0,1fr)_auto_auto] items-center gap-3 px-4 py-3.5 sm:grid-cols-[minmax(0,1fr)_120px_92px] sm:px-5"><div className="min-w-0"><p className="truncate text-xs font-bold text-foreground">{segment.label}</p><p className="mt-1 text-[10px] text-muted-foreground">{segment.customers} clientes</p></div><div className="text-right"><p className="text-xs font-bold text-foreground">{formatCurrency(segment.revenue)}</p><p className="mt-1 text-[10px] text-muted-foreground">receita</p></div><div className="text-right"><p className="text-xs font-bold text-accent">{segment.conversion}</p><p className="mt-1 text-[10px] text-muted-foreground">{segment.trend}</p></div></div>)}</div></article></section>

      {exportMessage ? <div className="flex items-center gap-2 rounded-xl border border-success/20 bg-success/5 px-4 py-3 text-xs font-semibold text-success"><Check className="h-4 w-4" /> {exportMessage}</div> : null}
      <Modal open={exportOpen} onClose={() => setExportOpen(false)} title="Exportar relatório" description="Escolha o recorte que será preparado para a sua equipa." footer={<><Button variant="ghost" size="sm" onClick={() => setExportOpen(false)}>Cancelar</Button><Button variant="accent" size="sm" onClick={() => { setExportMessage("Relatório preparado com os dados do período seleccionado."); setExportOpen(false); }}><Download className="h-3.5 w-3.5" /> Preparar ficheiro</Button></>}><div className="space-y-3"><div className="grid gap-2 sm:grid-cols-2">{["Visão executiva", "Performance por canal", "Clientes e segmentos", "Pedidos atribuídos"].map((item) => <button key={item} type="button" className="rounded-xl border border-border-subtle bg-card p-3 text-left text-xs font-semibold text-muted-foreground transition-colors hover:border-accent hover:bg-accent/5 hover:text-foreground">{item}</button>)}</div><div className="flex items-start gap-2 rounded-xl border border-border-subtle bg-muted/20 p-3 text-[11px] leading-relaxed text-muted-foreground"><CalendarDays className="mt-0.5 h-3.5 w-3.5 shrink-0" /> O ficheiro será preparado para {period.toLowerCase()}.</div></div></Modal>
    </div>
  );
}
